config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :sessions => 'sessions' }

  root 'welcome#index'

  resources :quiz
  resources :users
  resources :themes
  resources :rankings
  resources :profile
  resources :interest_profile
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :interest_profile

  post 'ranking' => 'rankings#index'

  resources :parliamentarians, :except => [:show] do
    get 'parliamentarians_per_party', :on => :collection
    get 'parliamentarians_per_state', :on => :collection
  end

  post 'parliamentarians_search' => 'parliamentarians#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
	before_action :get_user, only: [:edit, :update]

	def new
	end

	def create
		@user = User.find_by(email: params[:password_resets][:email].downcase)
		if @user
			@user.create_reset_digest
			@user.send_password_reset_email
			flash.now[:info] = "Enviado email com instruções para redefinir a senha"
			redirect_to root_url
		else
			flash.now[:danger] = "Endereço de email não encontrado"
			render 'new'
		end
	end

	def edit
	end

	def update
    if @user.password_reset_expired?
      flash[:danger] = "O tempo para redefinição de senha expirou"
      redirect_to new_password_reset_path
    elsif @user.update_attributes(user_params)
      if (params[:user][:password].blank? &&
          params[:user][:password_confirmation].blank?)
        flash.now[:danger] = "Senha e confirmação de senha não podem estar em branco"
        render 'edit'
      else
        flash[:success] = "A senha foi redefinida com sucesso"
        sign_in @user
        redirect_to @user
      end
    else
      render 'edit'
    end
  end

	private
		def user_params
      params.require(:user).permit(:password, :password_confirmation)
    end

		def get_user
			@user = User.find_by(email: params[:email])
			unless @user && @user.authenticated?(:reset, params[:id])
				redirect_to root_url
			end
		end
end

app/views/password_resets/edit.html.erb
<h1> Redefinir Senha </h1>
<%= form_for @user, url: password_reset_path do |f| %>
	<%= render 'shared/error_messages' %>
	<%= hidden_field_tag :email, @user.email %>

  <%= f.label :password, "Senha" %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmação de Senha" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Atualizar Senha" %>
<% end %>

app/views/password_resets/new.html.erb
<p id="notice"><%= notice %></p>

<h1> Esqueci a senha </h1>

<%= render 'shared/show_flashes' %>

<%= form_for(:password_resets, url: password_resets_path) do |f| %>
	<p>
	<%= f.label :email %>
  <%= f.text_field :email %>
	<p>
	<p><%= f.submit 'Enviar' %>	</p>
<% end %>