config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :sessions => 'sessions' }

  root 'welcome#index'

  resources :quiz
  resources :users
  resources :themes
  resources :rankings
  resources :profile
  resources :interest_profile
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :interest_profile

  post 'ranking' => 'rankings#index'

  resources :parliamentarians, :except => [:show] do
    get 'parliamentarians_per_party', :on => :collection
    get 'parliamentarians_per_state', :on => :collection
  end

  post 'parliamentarians_search' => 'parliamentarians#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
end

app/models/parliamentarian.rb
class Parliamentarian < ActiveRecord::Base
  has_many :propositions
  validates :id, presence: true, length: {maximum: 11}

  def self.search(search)
    if search
# :nocov:
      where(['name LIKE ?', "%#{search}%"])
# :nocov:    
    else
      take(600)
    end
  end
end

app/controllers/parliamentarians_controller.rb
class ParliamentariansController < ApplicationController
  def index
    @parliamentarians = Parliamentarian.search(params[:search])
    @ordened_states = order_states(Parliamentarian.select(:state).distinct)
    @ordened_partys = order_partys(Parliamentarian.select(:party).distinct)
  end

  def new
    @parliamentarian = Parliamentarian.new
    render nothing: true
  end

  def order_states(state)
    state  = state.to_a
    state.sort! {|a,b| a.state <=> b.state}
  end

  def order_partys(party)
    party  = party.to_a
    party.sort! {|a,b| a.party <=> b.party}
  end

  def parliamentarians_per_state
    @selected_state = Parliamentarian.where(state: params[:id])
    respond_to do |format|
      format.js { render json: @selected_state }
    end
  end

  def parliamentarians_per_party
    @selected_party = Parliamentarian.where(party: params[:id])
    respond_to do |format|
      format.js { render json: @selected_party }
    end
  end
end

app/views/parliamentarians/index.html.erb
<script type="text/javascript">
  $(document).ready(function () {
    var states = document.getElementsByClassName('parliamentarians_state')

    for(var i = 0; i < states.length; i++) {
      states[i].addEventListener('click', click_state, false);
    }

    function get_parliamentarians_per_state(value) { // value = state acronym
      $.ajax({
        url: "/parliamentarians/parliamentarians_per_state",
        type: "GET",
        dataType: "json",
        data: {"id": value},
        success: function (response) {
            parliamentarian_list = document.getElementById('parliamentarian_list');

            parliamentarian_list.innerHTML = ""

            console.log(response)
            for(var i = 0; i < response.length; i++) {
              parliamentarian_list.innerHTML += "<div><ul><p align='center'><span><a href='/profile/" + response[i].id +  "'><img src='" + response[i].url_photo + "'></a></span></p><p align='center'><b><a href='/profile/" + response[i].id +  "'> " + response[i].name + "</a></b></p><li align='left'> Partido: " + response[i].party + "</li><li align='left'>Estado: " + response[i].state + "</ul></div>";
            }
        },
        error: function () {
            parliamentarian_list = document.getElementById('parliamentarian_list');

            parliamentarian_list.innerHTML = "<h3>Erro ao tentar obter parlamentares</h3>"

        }
      });
    }

    function click_state() {
      var value = $(this).text();

      get_parliamentarians_per_state(value.trim());
      $('#drop1').foundation('dropdown', 'close', $('#drop1'));
    }
  });
  $(document).ready(function () {
    var partys = document.getElementsByClassName('parliamentarians_party')

    for(var i = 0; i < partys.length; i++) {
      partys[i].addEventListener('click', click_party, false);
    }

    function get_parliamentarians_per_party(value) { // value = party acronym
      $.ajax({
      url: "/parliamentarians/parliamentarians_per_party",
        type: "GET",
        dataType: "json",
        data: {"id": value},
        success: function (response) {
            parliamentarian_list = document.getElementById('parliamentarian_list');

            parliamentarian_list.innerHTML = ""

            console.log(response)
            for(var i = 0; i < response.length; i++) {
            parliamentarian_list.innerHTML += "<div><ul><p align='center'><span><img src='" + response[i].url_photo + "'></span></p><p align='center'><b><a href='/profile/" + response[i].id +  "'> " + response[i].name + "</a></b></p><li align='left'> Partido: " + response[i].party + "</li><li align='left'>Estado: " + response[i].state + "</ul></div>";
            }
        },
        error: function () {
            parliamentarian_list = document.getElementById('parliamentarian_list');

            parliamentarian_list.innerHTML = "<h3>Erro ao tentar obter parlamentares</h3>"

            }
      });
    }

    function click_party() {
      var value = $(this).text();

      get_parliamentarians_per_party(value.trim());
      $('#drop2').foundation('dropdown', 'close', $('#drop2'));
    }
  });
</script>
<div class="row">
  <div class="small-12 columns">
    <div class="off-canvas-wrap" data-offcanvas>
      <div class="inner-wrap">
        <div class="large-0 pull-0 columns">
          <nav class="top-bar show-for-medium-up" data-topbar>
            <ul class="title-area">
              <li class="name">
                <h1><a href="#">Perfil Parlamentar</a></h1>
              </li>
          </nav>
            <dl class="sub-nav">
              <p><dd><button data-dropdown="drop1" aria-controls="drop1" aria-expanded="false">Estados &raquo;</button></dd>
              <dd><button data-dropdown="drop2" aria-controls="drop2" aria-expanded="false">Partidos &raquo;</button></dd>
              <%= form_tag parliamentarians_path, method: :get do %>
                <div class="small-5 columns">
                  <%= text_field_tag :search, params[:search], id:"right-label", placeholder: "Nome do Parlamentar" %>
                </div>
                <div class="small-3 columns">
                  <button name="Buscar" type="submit" class="button postfix">Buscar</button>
                </div></p>
              <%end%>
            </dl>
          <ul id="drop1" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
            <ul id="drop" class="[tiny small medium large content]f-dropdown" data-dropdown-content>
            <div style="height:400px;line-height:3em;overflow:scroll;padding:3px;">
              <% @ordened_states.each do |p| %>
                <li> <a class="parliamentarians_state"> <%= p.state %> </a> </li>
              <%end%>
            </ul>
          </ul>
          <ul id="drop2" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
            <ul id="drop" class="[tiny small medium large content]f-dropdown" data-dropdown-content>
            <div style="height:400px;line-height:3em;overflow:scroll;padding:3px;">
              <% @ordened_partys.each do |p| %>
                <li> <a class="parliamentarians_party"> <%= p.party %> </a> </li>
              <%end%>
            </ul>
          </ul>
          <div id="parliamentarian_list" style="width:940px;height:800px;line-height:3em;overflow:scroll;padding:5px;">
            <div>
              <% if !params[:search].blank? %>
                <ul>
                <% @parliamentarians.each do |p| %>
                  <p align="center"><span><img src="<%= p.url_photo %>"/></span></p>
                  <ul class="pricing-table">
                    <li class="title"><%= p.name %></li>
                    <li class="price">Partido: <%= p.party %></li>
                    <li class="bullet-item" align="center"><a href="#"><%= link_to 'Ver Perfil', profile_path(p) %></a></li>
                  </ul>
                <%end%>
                </ul>
              <%end%>
            </div>
          </div>
        </div> 
      </div>
    </div>
  </div>
</div>