config/routes.rb
Rails.application.routes.draw do

  get 'welcome/index'
  devise_for :users, :controllers => {:omniauth_callbacks => "omniauth_callbacks", :sessions => 'sessions' }

  root 'welcome#index'

  resources :quiz
  resources :users
  resources :themes
  resources :rankings
  resources :profile
  resources :interest_profile
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :interest_profile

  post 'ranking' => 'rankings#index'

  resources :parliamentarians, :except => [:show] do
    get 'parliamentarians_per_party', :on => :collection
    get 'parliamentarians_per_state', :on => :collection
  end

  post 'parliamentarians_search' => 'parliamentarians#index'
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= favicon_link_tag 'favicon.ico' %>

    <title><%= content_for?(:title) ? yield(:title) : "Espelho Político" %></title>
    <%= include_gon %>
    <%= javascript_include_tag "application" %>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <div class="fixed">
    <nav class="top-bar foundation-bar" data-topbar>
      <ul class="title-area">
        <li class="name">
         <span data-tooltip class="has-tip"><h1 class="show-for-small-only"><a href="#"><%= link_to 'Espelho Político', root_url %></a></h1></span>
         <span data-tooltip class="has-tip"><h1 class="show-for-medium-only"><a href="#"><%= link_to 'Espelho Político', root_url %></a></h1></span>
         <span data-tooltip class="has-tip"><h1 class="show-for-large-only"><a href="#"><%= link_to 'Espelho Político', root_url %></a></h1></span>
        </li>
      </ul>
      <section class="top-bar-section">
        <!-- Right Nav Section -->
      <ul class="right">
        <li class="active"><a target="_blank"><%= link_to 'Início', root_url %></a></li>
        <li class="active"><a target="_blank"><%= link_to 'Perfil Parlamentar', parliamentarians_path %></a></li>
        <li class="active"><a target="_blank"><%= link_to 'Rankings', rankings_path %></a></li>
        <li class="active"><a target="_blank"><%= link_to 'Quiz', quiz_index_path %></a></li>
        <li class="active"><a target="_blank">Sobre</a></li>
         <% if user_signed_in? %>
          <li class="active"><a target="_blank"><%= link_to current_user.name, edit_user_registration_path %></a></li>
          <li class="active"><a target="_blank"><%= link_to 'Perfil de Interesse', interest_profile_index_path %></a></li>
          <li class="active"><a target="_blank"><%= link_to 'Sair', destroy_user_session_path, :method => :delete %></a></li>
        <% else %>
          <li class="active"><a target="_blank"><%= link_to 'Entrar', new_user_session_path %></a></li>
        <% end %>
      </ul>
    </section>
  </nav>
  </div>
  <div class="row">
    <div class="large-12 columns">
        <h2><center><img src="/ep.png"/></center></h2>
    </div>
  </div>
 <%=yield%>
    <%= javascript_include_tag "application" %>
  </body>
</html>